### ISSUE TITLE
Future systemd compatibility

### ISSUE THREAD

**Issue by bobafetthotmail** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#10]
I have reworked folder2ram (the script doing the leg work for this plugin) to (also) run with systemd.

I made a branch of this plugin that has been modified to operate the new version of folder2ram, so when the time comes, you can merge it to have a plugin that works with systemd too.

**Comment by happyreacer** [comment]
i have test the plugin 3.0 with omv 3.0.13 amd64 and have on activation an error:
`Failed to execute command 'folder2ram -autostartsystemd 2>&1 && systemctl start folder2ram 2>&1': folder2ram is a script-based utility that relocates the contents of a folder to RAM and on shutdown unmounts it safely synching the data back to the permanent storage. There are four main components of folder2ram system: --the init script in /etc/init.d or the systemd service in /etc/folder2ram that calls this main script on boot and shutdown --the main script in /etc/sbin/folder2ram --the configuration file in /etc/folder2ram/folder2ram.conf --the folders in /var/folder2ram, the bind-mounted folders they allow easy access to the original folder in permanent storage since if you mount folder A on folder B you lose access to folder B this trick allows access to B, allowing synching with the tmpfs at will for first startup use -configure action, edit the mount points as you wish, then -mountall list of actions (only one at a time): -enableinit ::::::::::sets up an appropriate autostart/stop init script, does not start it -enablesystemd ::::::::::sets up an appropriate autostart/stop systemd service, does not start it -disableinit ::::::::::removes the autostart/stop init script and unmounts all mount points -disablesystemd ::::::::::removes the autostart/stop systemd service and unmounts all mount points -safe-disableinit ::::::::::removes the autostart/stop init script but unmounts only at shutdown (hence safely) ::::::::::it also works if folder2ram is unistalled shortly afterwards -safe-disablesystemd ::::::::::removes the autostart/stop systemd service but unmounts only at shutdown (hence safely) ::::::::::it also works if folder2ram is unistalled shortly afterwards -status ::::::::::print all mountpoints and their status (mounted or unmounted) -syncall ::::::::::sync to disk the content of folder2ram's tmpfs folders -mountall ::::::::::folder2ram will mount all folders in the config file -umountall ::::::::::folder2ram will unmount all folders in the config file -configure ::::::::::folder2ram will open the configuration file in a text editor -reset ::::::::::restore default config file -clean ::::::::::unmounts all folders then removes any autostart Failed to start folder2ram.service: Unit folder2ram.service failed to load: No such file or directory.`

and on detail:

```
Fehler #4000:
exception 'OMVException' with message 'Failed to execute command 'folder2ram -autostartsystemd 2>&1 && systemctl start folder2ram 2>&1': 
folder2ram is a script-based utility that relocates the contents of a folder to RAM
and on shutdown unmounts it safely synching the data back to the permanent storage.

There are four main components of folder2ram system:
--the init script in /etc/init.d or the systemd service in /etc/folder2ram that calls this main script on boot and shutdown
--the main script in /etc/sbin/folder2ram
--the configuration file in /etc/folder2ram/folder2ram.conf
--the folders in /var/folder2ram, the bind-mounted folders
  they allow easy access to the original folder in permanent storage
  since if you mount folder A on folder B you lose access to folder B
  this trick allows access to B, allowing synching with the tmpfs at will

for first startup use -configure action, edit the mount points as you wish, then -mountall

list of actions (only one at a time):

-enableinit
::::::::::sets up an appropriate autostart/stop init script, does not start it
-enablesystemd
::::::::::sets up an appropriate autostart/stop systemd service, does not start it
-disableinit
::::::::::removes the autostart/stop init script and unmounts all mount points
-disablesystemd
::::::::::removes the autostart/stop systemd service and unmounts all mount points
-safe-disableinit
::::::::::removes the autostart/stop init script but unmounts only at shutdown (hence safely)
::::::::::it also works if folder2ram is unistalled shortly afterwards
-safe-disablesystemd
::::::::::removes the autostart/stop systemd service but unmounts only at shutdown (hence safely)
::::::::::it also works if folder2ram is unistalled shortly afterwards
-status
::::::::::print all mountpoints and their status (mounted or unmounted)
-syncall
::::::::::sync to disk the content of folder2ram's tmpfs folders
-mountall
::::::::::folder2ram will mount all folders in the config file
-umountall
::::::::::folder2ram will unmount all folders in the config file
-configure
::::::::::folder2ram will open the configuration file in a text editor
-reset
::::::::::restore default config file
-clean
::::::::::unmounts all folders then removes any autostart
Failed to start folder2ram.service: Unit folder2ram.service failed to load: No such file or directory.' in /usr/share/openmediavault/engined/module/flashmemory.inc:91
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/config.inc(206): OMVModuleFlashmemory->startService()
#1 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#2 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpcservice.inc(158): OMVRpcServiceAbstract->callMethod('applyChanges', Array, Array)
#4 /usr/share/openmediavault/engined/rpc/config.inc(224): OMVRpcServiceAbstract->callMethodBg('applyChanges', Array, Array)
#5 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#6 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('applyChangesBg', Array, Array)
#8 /usr/sbin/omv-engined(500): OMVRpc::exec('Config', 'applyChangesBg', Array, Array, 1)
#9 {main}

```

The installing works without error

**Comment by bobafetthotmail** [comment]
It seems that the package in the repo isn't in sync with the source code.
I just updated the changelog to get a "new" version with the current status of the plugin, since the 3.0 seems to be an older version of the plugin.
ryecoaaron will have to upload the "new" version in the repo.

@ryecoaaron how is handled packaging for the plugins? you do it manually or is there some automated package builder triggered by the version bump in the changelog?

**Comment by ryecoaaron** [comment]
Should all be current now. I do it all manually. I am following the repos now so i know when updates are released. Usually I release when changelog is updated.

**Comment by happyreacer** [comment]
it works now

**Comment by bobafetthotmail** [comment]
cool, will need to remember to update the changelog then.
