### ISSUE TITLE
MDADM reports an error when booting after enabling flashmemorry

### ISSUE THREAD

**Issue by Etren-zz** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#23]
OMV Version is 5.3.8-1(Usul)
Kernel Version is Linux 5.3.18-2-pve
flashmemory Version is 5.0.2

I newly installed OMV and enabled the PVE kernel.
When I configure omv according to Notes (optional), I get mdadm error when restarting omv.

`mdadm: No arrays found in config file or automatically`

But I didn‘t enable any options related to mdadm and RAID.
I used the Google search method to try to fix the error, but nothing improved.
After several attempts to newly install OMV, I determined that the above mdadm error was due to the flashmemory plugin being enabled.
How can I fix this?

**Comment by ryecoaaron** [comment]
It is not really caused by the flashmemory plugin.  The flash memory plugin adds mount points but since you most likely didn't mount any filesystems, mdadm seems to have a bug where it gets angry if there are no disks other than the OS.  Adding a line like the following to /etc/mdadm/mdadm.conf would most likely "fix" the problem.
`ARRAY <ignore> devices=/dev/sda`
However, the plugin should not do this because you might have an array on that drive and/or adding filesystems will fix the issue.  Not many people run OMV without storage drives.

**Comment by Etren-zz** [comment]
thank you for your reply.

This problem occurs after swap partitions according to the "Notes (optional)" operation of flashmemory.

If I just enable the flashmemory plugin, no mdadm error will occur.

**Comment by ryecoaaron** [comment]
Ok, I will add to the instructions to do the following IF you disable swap:

`rm /etc/initramfs-tools/conf.d/resume `
`update-initramfs -u`

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/commit/e2a3659e05d9bed39a3589fca42bc905323592d7
5.0.3 in the repo now.
