### ISSUE TITLE
Increased boot time

### ISSUE THREAD

**Issue by tooomm** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#27]
After following the steps as asked for in the plugin page in the OMV GUI and disabling+deleting swap...
boot time increased (~doubled) and I now see a blinking underscore on black screen for like 20s before the system performs some more steps and the OMV welcome message is finally displayed. The steps logged are also twice as many as before.

Can I provide you with some more details or output in case this is not normal, intended behavior?

I'm using OMV 5.5.4-1 and flashmemory 5.0.7.

**Comment by ryecoaaron** [comment]
The plugin doesn't directly cause this.  It has to do with initramfs looking for swap.  There are a few threads about this on the forum.

**Comment by tooomm** [comment]
For reference:
After searching the forums I found this thread for example: https://forum.openmediavault.org/index.php?thread/32649-remove-turn-off-folder2ram/

I recreated `/etc/initramfs-tools/conf.d/resume` and put the suggested line in.
After updating initramfs, the startup is now faster again. 👍
One `[ FAILED ]` message about the missing swap is still shown.

As user "gderf" with the helpful suggestion pointed out, it looks like the plugin instructions got changed at one point. Maybe this addition should be part of the notes as well? Or are there unmentioned drawbacks?

**Comment by ryecoaaron** [comment]
The instructions were changed because there was nothing about the swap before other than commenting the line out.  The different methods of fixing the boot messages seem to have different behaviors on different architectures.  I don't have time to test everything and just tried put what people were successfully using at the time.  I would rather just point to instructions that someone else was maintaining.

If you would like to update your PR to change the instructions, that is fine.  I just try to not to change the text all the time because then it has to be translated which doesn't happen for months sometimes.

**Comment by tooomm** [comment]
I understand your concerns. Maybe we can find a good solution.

**Comment by ryecoaaron** [comment]
closing due to age.
