### ISSUE TITLE
User should be informed (again) to disable swap

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#31]
Back in OMV5 days, this plugin recommended to disable swap, this is not the case anymore. I think this plugin should alert the user to disable SWAP or move SWAP to an SSD if possible, otherwise the job is not complete: not fully "preserving" the lifespan of the media and causing high performance drawbacks.

I have been running OMV6 with swap enabled on my thumb drive for about a year. 

On OMV6 I always experienced performance issues [(forum post)](https://forum.openmediavault.org/index.php?thread/48619-high-iowait-and-slow-copy-for-no-apparent-reason), caused by excessive I/O wait when doing simple copies or when running SnapRAID jobs. This triggered every day email alerts, because often `loadavg` was often above 5, even during simple activities.

I have finally I found the time to analyze the issue, and is swap indeed: as soon as I switched to a swapfile on my NVMe drive, performance is stellar, no more eccessive I/O wait, SMB performance is capping the 1Gbps and so on.

**Comment by ryecoaaron** [comment]
I removed the swap disable instructions because people failed to do it correctly too often.  People also should be doing something about swap a lot of times and aren't using this plugin.  I kind of feel like there should be a swap plugin to configure things.

**Comment by auanasgheps** [comment]
I get it, for a basic user these task can be overwhelming.

Also, might be more convenient to switch to a swapfile on a faster drive like I did.

Yeah, a swap plugin would perfectly fill this gap, but I get that might be a complex task. Maybe we could just link a Wiki article that describes the possible scenarios.

**Comment by bobafetthotmail** [comment]
this is also an OMV issue with swapping or swap priority (why is it swapping when you have 4gb free RAM), not an issue with this plugin. I think you should also open a bug to OMV itself https://github.com/openmediavault/openmediavault/issues 

that said, from what I see in the git history https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/blob/a44de9539a62e2163f2286811d9d9c99d45f313b/var/www/openmediavault/js/omv/module/admin/storage/flashmemory/Settings.js
the old instructions were just to comment the swap from the fstab, swapoff then wipe the swap partition to prevent automount. So even that was not great.

I agree with @ryecoaaron that it would just shift the issue (now all the people that actually needed swap would have OMV crashing because of "out of memory") and the only real solution is either a swap manager plugin that can remove the swap from main drive and replace it with a swapfile in the data drive array or OMV natively does this automatically.

**Comment by PrplHaz4** [comment]
A plugin would be great, but I don't think we have clear guidance on what the plugin would even do, or what conventions should be followed (back to the wiki suggestion above being a good place to start).

IMO one of the reasons we see a lot of swap issues is the documented prerequisites seems to understate the required space (or is unclear on a more realistic recommendation).  4GiB does not seem to be enough for even a basic install (2GiB system + 2GiB swap?).  Now start hosting containers, upgrading your RAM, generate a lot of logs and you are easily in the 32GiB range.  All of a sudden you need to figure out upgrading and re-partitioning your system disk, resizing/moving/removing swap file...etc.

> System Drive: min. 4 GiB capacity (but more than the capacity of the RAM)
> Note: The whole disc will be occupied by the system and swap space [[1]](https://docs.openmediavault.org/en/stable/prerequisites.html#id7), so size doesn’t matter so much. Data storage on the system disc is not supported.

A decision tree or "typical" setups might be helpful for initial setup, but there's still the missing piece of "adjusting" things as your system changes and grows.

**Comment by bobafetthotmail** [comment]
Heh since a NAS does not really need hybernation (which requires a swap partition as big as the RAM) there is no real strict rule.

Best you get is rules of thumb online. It's more or less 2*RAM until you go past some threshold like 8GB or 16GB and then it becomes 1*RAM, and after you pass another threshold like say 32 or 64GB it's whatever small fraction of that you feel like is OK. I personally don't have any swap on systems with more than 32GB at all.

Swap partitions are required only for hybernation/resume (which is not a thing for a NAS) or for compatibility reasons. Swap files have the same performance and are much more flexible. All the usual linux filesystems (xfs, ext4, btrfs) support swapfiles. 
ZFS does not and has a special sauce way to add a swap zvol that may or may not be a good idea as mentioned in their own docs https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html?highlight=swap#step-7-optional-configure-swap

That said there are a couple system services in Debian that automatically create/resize swap files and mount/unmount them. 
A simpler one that allocates/updates/mounts a swap file that is (by default) 2*RAM 
https://manpages.debian.org/bookworm/dphys-swapfile/dphys-swapfile.8.en.html
a more advanced one that will keep adding swapfiles piecemeal as needed by memory pressure and then deleting them when they free up
https://manpages.debian.org/bookworm/swapspace/swapspace.8.en.html

So yeah this theoretical swap plugin would have de delete any default swap partition created by the installer (and from fstab) and autodetect or ask the user a path where the swapfile should be created (which would be preferably in the drive array if it's not ZFS). Then the applications above would do the leg work.

**Comment by auanasgheps** [comment]
I am closing this issue since there's no further activity/action
