### ISSUE TITLE
Reboot KByte Reporting FALSE

### ISSUE THREAD

**Issue by trancen** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#9]
After a reboot, I'm getting the word FALSE instead of total in KBytes, see attachments. 

Running 2.1.9 of OMV. 

![image](https://cloud.githubusercontent.com/assets/4571582/9412341/26a07d02-47f9-11e5-866e-7b18a4c7ed1c.png)

![image](https://cloud.githubusercontent.com/assets/4571582/9412348/2cce15b8-47f9-11e5-9297-15bbc1714b01.png)

**Comment by ryecoaaron** [comment]
Your root drive probably changed drive letters.  It only detects the root drive when installing the plugin.  I guess I can change it to detect all the time.

**Comment by trancen** [comment]
Yup that was it. I installed a Ext USB drive to copy some data, and noticed now that it was assigned /dev/sdc1 and not the USB Boot Drive. I manually went into /etc/openmediavault/config.xml edited the correct device and now it's reporting correctly the KBytes.

**Comment by STPKITT** [comment]
I experienced the following on two different OMV-machines both running OMV 2.1 with installed openmediavault-omvextrasorg 2.2 and flashmemory 1.9

First machine: this machine has exactly the same harddrives connected as was the case during install of the plugin. Despite that it shows Root as /dev/sda1 but the USB-boot-drive is /dev/sdc1, so the GUI shows the amount of Kbytes written to the sda1-HDD instead of the amount written to the USB-boot-drive.

Second machine: I had only the USB-boot-drive connected while installing the flashmemory-plugin. The GUI showed /dev/sda1 for Root, but at that time there was no /dev/sda1 in the whole system. The "Write Kbytes" said false. Since then I connected a single SATA-harddrive, which became /dev/sda1 while the boot-usb-drive stayed at /dev/sdb1. Since then instead of "false" the "Write Kbytes" on this machine shows the amount of data written to the sda1-HDD!

Conclusion: To me it seems the plugin always shows the amount of data written to /dev/sda1 no matter what and it says "false" when the is no /dev/sda1 in the system. Looks like a but to me!
Question: does the flashmemory plugin work as intended despite showing the wrong things in the GUI?

**Comment by ryecoaaron** [comment]
Read my comment two comments above yours.  The value is just a display of a file in the /sys directory. It has nothing to do with the function of the plugin.  If the boot drive letters change, it won't be updated.  I will look at fixing it.

**Comment by STPKITT** [comment]
Ok, looking forward to the fix then.
Great plugin and very important for OMV! Thanks for your work!
